language: bash
install:
  - sudo apt install openmp cmake boost
  - wget https://spcl.inf.ethz.ch/Research/Performance/LibLSB/liblsb-0.2.2.tar.gz && 
    tar xvf liblsb-0.2.2.tar.gz && 
    cd liblsb-0.2.2 && 
    ./configure &&
    make && sudo make install

script:
  - cd code
  - cmake && make
